spring:
  liquibase:
    change-log: db/master.xml
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
      path: /h2-console

